ALTER TABLE bots
  ADD COLUMN IF NOT EXISTS prompt_bot_name VARCHAR(200) DEFAULT '',
  ADD COLUMN IF NOT EXISTS prompt_bot_role VARCHAR(500) DEFAULT '',
  ADD COLUMN IF NOT EXISTS prompt_traits VARCHAR(500) DEFAULT '',
  ADD COLUMN IF NOT EXISTS prompt_tasks TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS prompt_address VARCHAR(20) DEFAULT 'ты',
  ADD COLUMN IF NOT EXISTS prompt_tone VARCHAR(100) DEFAULT '',
  ADD COLUMN IF NOT EXISTS prompt_emoji VARCHAR(200) DEFAULT '',
  ADD COLUMN IF NOT EXISTS prompt_structure VARCHAR(200) DEFAULT '',
  ADD COLUMN IF NOT EXISTS prompt_format TEXT DEFAULT '';
